name: Manual Production Deployment

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Add SSH key to the agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Add server to known hosts server
        run: ssh-keyscan -H 35.78.70.162 >> ~/.ssh/known_hosts

      - name: Deploy to Production Server
        run: |
          echo "Deploying to production server"
          ssh ubuntu@35.78.70.162 'set -e; docker pull sanoj8860/reactjs-app:${{ github.sha }} && docker rm -f reactContainer || true && docker run -d -p 80:80 --name reactContainer sanoj8860/reactjs-app:${{ github.sha }}'
