name: Merged Request CI/CD
on:
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  build-test:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t sanoj8860/reactjs-app:${{ github.sha }} .

      - name: Publish Docker Image to Docker Hub
        run: docker push sanoj8860/reactjs-app:${{ github.sha }}

      - name: Add SSH key to the agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Add server to known hosts server
        run: ssh-keyscan -H 35.78.70.162 >> ~/.ssh/known_hosts

      - name: Deploy to Development Server
        run: |
          echo "Deploying to development server"
          ssh ubuntu@35.78.70.162 'set -e; docker pull sanoj8860/reactjs-app:${{ github.sha }} && docker rm -f reactContainer || true && docker run -d -p 80:80 --name reactContainer sanoj8860/reactjs-app:${{ github.sha }}'